### ISSUE TITLE
[potential bug] 3d view stays empty?

### ISSUE THREAD

**Issue by neuronflow** [scalableminds/webknossos#6873] opened 2023-02-23 09:05 UTC
## Context

https://pwild.helmholtz-munich.de/datasets/iterm/full-resolution_combined

## Expected Behavior

3d view should show data

## Current Behavior

3d view stays empty
## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

open https://pwild.helmholtz-munich.de/datasets/iterm/full-resolution_combined

## Your Environment for bug

latest OSX, latest chrome + latest firefox

**Comment by philippotto** [comment] 2023-02-27 11:04
Thank you for the bug report + reproduction link! We will look into this. My initial hunch is that this is caused by the voxel size being relatively large (1.63 × 1.63 × 6 µm³/voxel). If you are blocked by this issue, you might want to try to change the voxel size (e.g., to 1.63 × 1.63 × 6 **nm**³/voxel) as a temporary workaround.

Related to #6577.

**Comment by philippotto** [comment] 2023-03-06 14:19
Good news! This should already have been fixed by https://github.com/scalableminds/webknossos/pull/6221. However, you are using an older version of wK which is why you are still seeing the error. I'd recommend to update (at least to 22.06.0) to fix this. Let me know in case you are still having problems.

**Closed by philippotto** 2023-03-06 14:19 UTC
Labels: bug, frontend
