### ISSUE TITLE
Frontend analytics

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5348] opened 2021-03-30 14:17 UTC
## Detailed Description
Events to track (to be extended):
- [ ] Open sharing modal (annotation)
- [ ] Open dataset settings
- [ ] Open upload view
- [ ] Add files to upload view
- [ ] Customize layout (i.e. move panels, resize panels)
- [ ] Store custom layout
- [ ] Load custom layout

## Context
We have analytics on the backend, but we cannot track everything from the backend

**Comment by fm3** [comment] 2021-03-31 08:37
Duplicate of #5296 (I copied the todo list to there so nothing is lost)

**Closed by fm3** 2021-03-31 08:37 UTC
Labels: enhancement, frontend
