### ISSUE TITLE
NML Format: Allow parameters.experiment.name to be empty

### ISSUE THREAD

**Issue by georgwiese** [scalableminds/webknossos#3692] opened 2019-01-28 10:57 UTC
When we auto-generate NMLs, we don't necessarily know what the dataset name in WebKnossos will be. However, if it doesn't match, we can't open the NML, even when we drag the NML into an open skeleton tracing of the correct dataset.

I think it should be possible to leave the name empty. The current behavior could stay the same if the name is set and different from the dataset name.

**Comment by philippotto** [comment] 2019-01-30 09:09
Probably a duplicate of #3690 ?

**Closed** 2019-02-04 16:07 UTC
