### ISSUE TITLE
exploreAndAddRemote should also work with local file path

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#7380] opened 2023-10-11 19:21 UTC
## Detailed Description
The exploreAndAddRemote should also work with local absolute file path as `remoteUri`. We should add a conf entry with a list of white-listed path prefixes to restrict the datasets that can be imported.

**Comment by fm3** [comment] 2023-10-16 14:08
duplicate of resolved #7387

**Closed by fm3** 2023-10-16 14:08 UTC
Labels: enhancement, backend
