### ISSUE TITLE
Tree tab content only appears after re-switching to it

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#4072] opened 2019-05-07 09:48 UTC
[Link to Discuss](https://discuss.webknossos.org/t/no-trees/1464)

**Comment by daniel-wer** [comment] 2019-05-09 17:54
Should be fixed by #4083

**Comment by daniel-wer** [comment] 2019-05-09 20:56
Did not fix the issue, unfortunately :/

**Comment by fm3** [comment] 2020-10-09 12:37
@daniel-wer is this a duplicate of #4807 (and thus closed by #4816)?

**Comment by daniel-wer** [comment] 2020-10-09 14:22
Yes, good find, I'll close it :)

**Closed by daniel-wer** 2020-10-09 14:22 UTC
Labels: bug, frontend
