### ISSUE TITLE
Ipad in browser flight mode

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#1318] opened 2016-07-04 21:29 UTC
Not necessarily g-sensor, buttons would be fine. Unbelievably great, and the direct transition to the games. 

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1318/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment] 2017-08-22 14:20
Closing as duplicate of #563

**Closed by hotzenklotz** 2017-08-22 14:20 UTC
Labels: flight, frontend, new feature
