### ISSUE TITLE
switch on and off multiple trees

### ISSUE THREAD

**Issue by deployboy** [scalableminds/webknossos#630] opened 2015-07-24 08:38 UTC
So currently we can either show all trees, no trees (by pressing 1) or one tree (by pressing 2). Wouldn't it be neat to be able to show any subset? Perhaps the tree list could be a checkbox list?

 Reported by: Kevin Boergens (boergens@neuro.mpg.de) on master

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/630/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment] 2017-07-28 13:45
Duplicate of #1921

**Closed by hotzenklotz** 2017-07-28 13:45 UTC
Labels: frontend, new feature
