### ISSUE TITLE
Forced garbage collection of buckets

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5000] opened 2020-12-18 08:00 UTC
Airbrake still shows some `Error:  Unhandled Rejection: "Error: Unexpected state: UNREQUESTED"` errors (https://scm.airbrake.io/projects/95438/groups/2737723584692415595?tab=notice-detail). See #4895 where we also noticed this. The latter issue was closed, since we identified one major culprit for these messages. However, I think, I found another culprit.

When looking at the logs in Airbrake, one often sees that this message correlates with the UNREQUESTED-error:
`A bucket was forcefully garbage-collected. This indicates that too many buckets are currently in RAM.`

We should find out why this happens and how to solve the root problem (namely that too many buckets are dealt with). And/or one could improve the handling of this situation. Currently, it's probably something like this:

- a bucket is requested (e.g., for rendering)
- lots of other buckets are also allocated (not exactly clear why)
- for these other buckets, not enough slots are available. therefore, the very first bucket is forcefully collected
- now, the request for the first bucket finishes. the bucket is re-created again and `receiveData` is called. however, the bucket is in the unrequested-state now.

My guess for the reason of the "too many buckets are currently in RAM"-symptom is one of the following:
- ~rapid movement to another position (or rapidly zooming), so that the old requests are basically outdated, but were already initiated. canceling these requests would be helpful, but also a bit difficult.~
  - hm, I just checked the pullqueue code and after the bucket buffer is received, `getBucket` (not `getOrCreateBucket`) is called. if the bucket doesn't exist, the buffer is ignored. so, my theory doesn't really add up.
- upsampling of volume data or other mechanisms which process buckets independent of the rendering pipeline
  - however, the error also occurs for skeleton-only data, so there has to be another reason
- ???

@daniel-wer do you have thoughts on this?

**Comment by daniel-wer** [comment] 2020-12-22 10:51
@philippotto I had a brief look at this as well, but haven't found a possible explanation yet. I also wasn't able to reproduce these issues.

As you already noted there seem to be two issues: (1) Too many buckets are allocated **and marked as not collectable** (meaning they are either accessed in the last render pass, dirty or currently requested). (2) `Unexpected state: UNREQUESTED` probably, because buckets were forcefully collected.

Good observation that these issues occur in skeleton-only annotations as well, because the volume data up/down-sampling would've been my first suspicion for (1) as well. From reading the code I cannot spot a possible explanation for (1). To investigate this, it could help to log `isSegmentation` and `elementClass` in the `A bucket was forcefully garbage-collected.` message as well, to check whether all layers are affected or only particular layers. We could also log this case to airbrake directly to get more accurate occurrence numbers (currently it's only visible if other errors happen, afterwards).

I also don't have a good explanation for (2), but I think this could be caused by complex interactions with the forcefully collected buckets. For example, in the example you "redacted", the timeline could've also been: Bucket A is requested -> Bucket A is forcefully collected -> Bucket A is accessed using `getOrCreateBucket` in any of the multiple other spots in the code and, therefore, created -> Bucket A is received -> `Error: Unexpected state: UNREQUESTED`. To debug this, it would be great to have the stack trace in airbrake, not sure whether that's possible in the `unhandledrejection` handler. This way we would at least know where `unexpectedState` was called from.

I would propose to add the additional logging, then focus on (1), but ideally also investigate (2).

**Comment by philippotto** [comment] 2020-12-22 16:55
> I also don't have a good explanation for (2), but I think this could be caused by complex interactions with the forcefully collected buckets. For example, in the example you "redacted", the timeline could've also been: Bucket A is requested -> Bucket A is forcefully collected -> Bucket A is accessed using getOrCreateBucket in any of the multiple other spots in the code and, therefore, created -> Bucket A is received -> Error: Unexpected state: UNREQUESTED.

Ah, that makes sense to me. During bucket picking and prefetching, `getOrCreateBucket` is likely to be called for a collected bucket which would instantiate it again. I'm wondering whether we should simply ignore the arrived bucket data. In the end, the scenario can be broken down to: an outdated request arrived. I think, it would be fine to simply ignore the payload. Ideally, this wouldn't happen, but since we cannot properly cancel the fetch-requests due to the batching, I don't see any other way to fix this (also I don't see any harm in doing so). Do you agree?

Nevertheless, the forceful bucket collection seems to be a thing which we should tackle properly. I agree, that more logs should be helpful here.

Ahhhh, I just got a hunch, what could explain the issue: If the user has a very beefy computer, the GPU might allow a very high amount of buckets for a data layer. If that amount exceeds 5000, the hard threshold of the `DataCube` is violated. I just had a look at airbrake to see logs of an affected user (for whom the hard collection was logged) and indeed I found the following:

![image](https://user-images.githubusercontent.com/2486553/102912961-60785900-447e-11eb-9471-88c192ca54a4.png)

This log output is not from the same session (since airbrake doesn't transfer all the logs), but I found another session from the user, where I could extract the above information.

I'm quite confident that this is the culprit :)

So, my suggestion would be:
- clamp the upper bucket capacity limit to 5000 (unify the constant first obviously)
- ignore arriving a bucket request if the bucket is in the unrequested state

Do you agree? Or should we omit the second step, since the error might raise fishy behavior in the future? :thinking: Would also be fine for me.

**Closed** 2021-01-21 10:03 UTC
