### ISSUE TITLE
Creating hybrid tracing should ask for new vs. existing segmentation

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4051] opened 2019-04-29 11:38 UTC
the backend should already support this, the frontend currently always sends `withFallback: true`

https://discuss.webknossos.org/t/creating-hybrid-tracing-should-ask-for-new-vs-existing-segmentation/1444

related: #3433

**Comment by philippotto** [comment] 2019-05-02 09:26
Duplicate of #4022 which is also closed by now.

**Closed by philippotto** 2019-05-02 09:26 UTC
Labels: frontend
