### ISSUE TITLE
selecting node in 3d viewport does not immediately change rotation center

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4472] opened 2020-03-10 13:05 UTC
if i shift+click a node in the 3d viewport the rotation center changes. however, it does so only after moving around a bit. would be nice if that could happen immediately

**Comment by MichaelBuessemeyer** [comment] 2020-04-13 11:18
@fm3 I cannot reproduce this bug. At least the way I understand you issue.
The code clearly sets the node selected with `shift+click` active. Then a saga / background process sets the position and rotation center to the active node.
Here is what happens on my laptop in chrome (the same goes for firefox):
![rotation-center](https://user-images.githubusercontent.com/39529669/79116541-11bfde80-7d89-11ea-846c-d1af262696ee.gif)
As you can see the rotation center is updated immediately or do I misunderstand you completely?

**Comment by fm3** [comment] 2020-04-13 11:28
Thanks for investigating this! Turns out my use case was more specific: I’m selecting the node _in the 3d viewport_. In fact, my view configuration showed _only_ the 3d viewport.

**Comment by MichaelBuessemeyer** [comment] 2020-04-13 14:52
@fm3 Thanks for your reply and description of how to reproduce this bug. However I still cannot reproduce this error, even when only the 3d viewport is visible. The rotation center is always immediately updated.
![rotation-center](https://user-images.githubusercontent.com/39529669/79130297-09769c00-7da7-11ea-8b86-0e7133ae63a3.gif)

Note: in both videos I selected the node via the 3d viewport.

**Comment by fm3** [comment] 2020-04-13 14:58
In the second video, right after you select the lower node you rotate again but it still rotates around the node on top for about two seconds, can you see what I mean? That’s my symptom. Not sure how to explain in more detail.

**Comment by MichaelBuessemeyer** [comment] 2020-04-13 16:04
@fm3 Thanks to your help I found the bug. The center wasn't updated immediately, only after an invisible animation. #4544 will remove the animation and therefore should resolve this bug :+1:

**Comment by MichaelBuessemeyer** [comment] 2020-04-14 11:09
The bug will be resolved with #4544 :tada:

**Closed** 2020-04-30 09:14 UTC
Labels: bug, frontend
