### ISSUE TITLE
Support neuroglancer precomputed datasets

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#7572] opened 2024-01-18 19:50 UTC
## Detailed Description
Webknossos supports neuroglancer precomputed datasets. However, it does not support the precomputed meshes yet. The mesh format is very similar to our mesh format so the frontend should already support it. The backend would need to detect the availability of meshes and adapt the necessary routes. 

Spec: https://github.com/google/neuroglancer/blob/master/src/datasource/precomputed/meshes.md#multi-resolution-mesh-format

**Comment by fm3** [comment] 2024-01-19 10:22
duplicate of #6826

**Closed by fm3** 2024-01-19 10:22 UTC
Labels: enhancement, backend
