### ISSUE TITLE
node comments: scroll bar is at top, but view is not scrolled all the way up?

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3604] opened 2019-01-08 12:50 UTC
saw this on shared screen during a call. chrome linux. there were many comments. worked in firefox. I did not yet try to reproduce it

**Comment by daniel-wer** [comment] 2019-01-08 13:43
This may be a duplicate of https://github.com/scalableminds/webknossos/issues/3492 and the second scrollbar was out of view. This is already fixed in https://github.com/scalableminds/webknossos/pull/3457, let's check after it is merged.

**Comment by fm3** [comment] 2019-01-08 13:44
Ah yes, it would probably be that. Thanks! I had only searched the open issues.

**Comment by daniel-wer** [comment] 2019-02-04 15:16
Let's reopen this if we encounter it again, I'm pretty it's fixed :)

**Closed by daniel-wer** 2019-02-04 15:16 UTC
Labels: bug, frontend
