### ISSUE TITLE
“Unknown Error occured” toast shortly flashes when navigating away during page loads

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#3122] opened 2018-08-28 06:14 UTC

**Comment by philippotto** [comment] 2018-10-02 14:52
@fm3 Do you know a reliable way to reproduce this? @MichaelBuessemeyer and I weren't able to reproduce it :/

**Comment by fm3** [comment] 2018-10-02 14:54
I don’t know a reliable way. When I’ll see it the next time, I’ll try to reproduce it reliably with that.

**Comment by MichaelBuessemeyer** [comment] 2019-01-20 20:02
As we can't reproduce this bug, I close this issue. If you can reproduce the bug, just re-open this issue :slightly_smiling_face:

**Closed by MichaelBuessemeyer** 2019-01-20 20:02 UTC
Labels: bug, can't reproduce, frontend, low-pri
