### ISSUE TITLE
Min/Max sliders instead of brightness/contrast

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3618] opened 2019-01-11 13:15 UTC
Currently wk has brightness and contrast sliders to adjust the data visualization. Some users say that they prefer min-max sliders instead (which is equivalent).
Really cool would be a histogram of the data currently in the viewports to support the min-max sliders.

**Comment by philippotto** [comment] 2019-01-14 08:52
Duplicate of #3583 :)

**Closed by philippotto** 2019-01-14 08:52 UTC
Labels: enhancement, frontend
