### ISSUE TITLE
Changes of dataset settings in “advanced” view are not accepted

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5465] opened 2021-05-06 10:28 UTC
(I have not yet investigated this further, not sure if this always happened or what the exact conditions were)

quoting from https://discuss.webknossos.org/t/changes-of-dataset-settings-in-advanced-view-are-not-accepted/1662

> I’ve tried to manually fix the issue in the “advanced” view.
>
> The green check mark in the text field indicates that the modified configuration is valid. (I’ve only removed one of the two color layers.) When clicking “save”, webKnossos shows a “Please check that all form fields are valid” toast. Based on the color coding, I assume that this is only an “info”, not an “error” (red).
> Still, it seems that the save operation failed. The segmentation layer does not show up in the tracing view despite being present in the dataset config.

**Comment by MichaelBuessemeyer** [comment] 2021-05-28 15:08
I thought about this bug a bit and here is my guess:
Because the synchronization between the simple and advanced settings tab might be messed up by the weird behaviour of `_.merge`, changing the settings in the advanced tab might have caused the settings in the simple tab to become faulty.
Thus I guess this bug might be resolved by #5492.

Another thing I noticed:
When the settings contain errors, the UI automatically switches to one of the tabs with errors.
If the datasource-properties settings have errors in the simple tab but the advanced tab is in focus then the UI does not switch to the simple tab view. This is likely the exact behaviour of the bug above: The error toast indicates that the settings have errors but none of them is in the advanced tab view.
=> Maybe automatically switching to the simple/advanced tab with the error could help the user figuring out, why there was an error :thinking: 

Update: I was able to reproduce the bug fairly easy:
1. Use a dataset with more than one color layer
2. Go to the advanced tab and remove one color layer
3. Try to save the settings. => this should fail exactly as in describe in the bug, without a hint on what is wrong.
4. Switch to the simple tab
5. Save the dataset again. Now it works. => Thus the syncronization between the tabs is likely at fault here

**Comment by MichaelBuessemeyer** [comment] 2021-05-28 15:42
The root cause is pretty likely the following:
If a dataset layer is removed, there are still form items left in the simple form for that layer. They cause the validation before sending the data to the backend to fail. Then if you switch back to the simple form, these form items are removed and thus you can successfully submit the changes.

**Closed** 2021-06-03 15:20 UTC
Labels: bug, frontend
