### ISSUE TITLE
Conversion to wkw should propagate unit

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#7956] opened 2024-07-29 11:28 UTC
When uploading image data to WK that needs to be converted, the provided unit should be propagated to the worker so that the unit is also encoded in the final dataset.

**Comment by fm3** [comment] 2024-08-20 09:56
duplicate of #7940, solved by https://github.com/scalableminds/webknossos/issues/7956 together with https://github.com/scalableminds/voxelytics/pull/3666

**Closed by fm3** 2024-08-20 09:56 UTC
Labels: enhancement
