### ISSUE TITLE
Dataset Settings View: applySuggestedSettings mixes up layers

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#5401] opened 2021-04-15 17:05 UTC
An additional color layer directory is linked into an existing dataset, without updating the datasource-properties.json on disk. Then the edit view is opened, where the suggestion to adapt additonal inferred information is accepted.

If this happens while the settings view is in “advanced” view, i.e. shows json, everything works as expected.

However, if the simple view is shown, the layers get mixed up, resulting in a duplicate of a previously existing layer, rather than the addition of the new layer. Switching to “advanced” then already shows the problem, but even if no such switch is performed, the broken settings are sent to the datastore upon hitting “Save”.

I already pushed a back-end side assertion on branch duplicate-layers, but while the front-end bug is in place, that would only move the error from postgres to the datastore, so I’m not opening a PR for that yet.

**Comment by MichaelBuessemeyer** [comment] 2021-05-14 16:53
@fm3 I am unable to reproduce this on branch `duplicate-layers`.
What I did:
- Create a copy of the color layer of the ROI dataset in the dataset's directory and name it "color2".
- Open the dataset's settings, open the advanced tab and accept the inferred JSON. => This worked fine (I did not submit the updated settings and only trusted the json frontend validation.)
- I reopened the dataset settings and applied the inferred JSON in the simple view. This created a new "color2" setting and the validation was alright. Changing to the advanced tab showed that the current JSON is also valid according to the frontend validation.


How can I properly reproduce the bug?

**Comment by fm3** [comment] 2021-05-14 16:59
I think the original bug occurred when you _don’t_ switch to the advanced tab. If that still doesn’t occur for you, we can have a look together next week :)

**Comment by MichaelBuessemeyer** [comment] 2021-05-14 17:16
When I accept the suggested changes in the simple version and then hit save everything still works correctly: I get the green toast informing me about the success of the update and I get redirected to the dashboard :thinking:
Opening the dataset in view mode also works perfectly fine.

**Comment by fm3** [comment] 2021-05-14 17:20
Hmm, then I don’t know what’s different 🤔 Could you try also with a segmentation layer? I don’t really see how that would be different but that was used in the original bug report.
Otherwise, sure, let’s look at it together then

**Comment by MichaelBuessemeyer** [comment] 2021-05-15 13:28
> Could you try also with a segmentation layer?

This is indeed a good idea :tada:. If I add a segmentation layer to a dataset, the frontend validation fails as the inferred JSON has `largestSegmentId : 0` set but the frontend validation requires a value `> 0` not `>= 0`.
This error is shown in both modes: simple and advanced (although the error description of the advanced mode is pretty much useless). 
Thus I think this bug could be fixed by a small change in the backend?

Beside this I cannot find any other bugs.

**Comment by fm3** [comment] 2021-05-17 06:17
Hmm no, this is not the problem that this issue is about. I can still reproduce it, also with a color layer. In fact, the largestSegmentId=0 is intended (or at least, as far as I know, unavoidable) since the back-end would have to search _all_ of the data to infer the real value. So instead the user is asked to supply it in the edit view. 🤔

**Comment by fm3** [comment] 2021-05-17 14:46
For the record: we noticed that the behavior depends on the ordering of the layers in the backend’s explore route. If the new layer is added last, things work fine.

**Comment by MichaelBuessemeyer** [comment] 2021-05-21 14:41
I tacked down the root cause of this bug: We use lodashs `merge` method to keep the simple and advanced view in sync and this methods behaviour is not as expected:
![image](https://user-images.githubusercontent.com/39529669/119154598-9a13b700-ba52-11eb-994e-33195bd48f16.png)
As you can see: After the merge lodash somehow manages it so rename the `newest` layer to `color` :confused:.
As we use this method to sync between those two tabs I suggest another implementation of this method: Instead of merging the values in the two tabs, we should just copy the values from one tab to the other. Then if this method is triggered each time the user switches between tabs, this should keep the tabs in sync. (I hope).

I chose this option of solving this bug without hopefully creating new ones as it is easier than trying to track down why lodash messes this merge up and implementing our own merge method with the help of `mergeWith` by lodash.

**Closed** 2021-06-01 10:18 UTC
Labels: bug, frontend
