### ISSUE TITLE
Volume tasks based on an annotation with fallback only uses the fallback

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5722] opened 2021-09-09 09:35 UTC
## Steps to Reproduce the bug

- [ ] Cannot reproduce the bug anymore / needs deeper investigation.

1. Create a volume annotation with fallback layer (therefore, the dataset needs to have a segmentation layer). Brush a bit over existing segmentation.
2. Copy the annotation ID from the URL
3. Create a task type with volume (or hybrid) if this does not exist yet
4. Create a task with the volume task-type and use "Use Annotation ID as Base" and paste the copied ID there
5. Go to dashboard and use "Get Task" and open the new task
6. The annotation only contains the original segmentation layer and not the data brushed in (1)

## Your Environment for bug

- Browser name and version: e.g. Chrome 39
- Operating System and version: e.g. Windows 10
- Version of WebKnossos (Release or Commit):
- [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
- [ ] Specific to webKnossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by fm3** [comment] 2022-04-25 09:14
We tested this some more and cannot reproduce this. Closing this until we get new reports

**Closed by fm3** 2022-04-25 09:14 UTC
Labels: bug, backend, can't reproduce, important
