### ISSUE TITLE
Allow to remove a volume tracing layer from an existing annotation

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6482] opened 2022-09-21 08:20 UTC
Allow to remove a volume tracing layer from an existing annotation. In case the layer is based on a fallback layer, the naming should probably be "restore original segmentation layer (warning: this will delete all the modifications you applied to it)" or something like that.

**Comment by fm3** [comment] 2022-09-21 08:34
duplicate of #5802

**Closed by fm3** 2022-09-21 08:34 UTC
Labels: backend, frontend
