### ISSUE TITLE
Change loading state title

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5062] opened 2021-01-20 12:39 UTC
When loading a dataset, the empty-state name is shown in the title which is `Test Dataset | Connectomics Department | webKnossos`. Can we change the title to `Loading | webKnossos` or just `webKnossos`?

**Comment by fm3** [comment] 2021-01-20 13:52
Duplicate of #5041

**Closed by fm3** 2021-01-20 13:52 UTC
Labels: frontend, low-hanging-fruit
