### ISSUE TITLE
Can we get rid of `Explorational` in the annotation Url?

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#5058] opened 2021-01-19 10:22 UTC
This is a minor issue, but I was wondering if we could get rid of the `Explorational` part of the url. Especially for published annotations, this particular choice of terminology is a bit weird.

<img width="356" alt="Screenshot 2021-01-19 at 11 16 06" src="https://user-images.githubusercontent.com/335438/105020562-bae9e280-5a47-11eb-89d2-73645b30c327.png">

**Comment by normanrz** [comment] 2021-01-21 16:12
@philippotto what is that part of the Url used for? Do you think we could easily get rid of it?

**Comment by philippotto** [comment] 2021-01-21 16:54
The front-end only needs the annotation type (explorational, task etc) to fetch the annotation-info via ``/api/annotations/${annotationType}/${annotationId}/info`. If the back-end doesn't need the `annotationType` in the url, the front-end wouldn't need it, either. At least, that's my current impression.

**Comment by normanrz** [comment] 2021-01-21 20:13
@fm3 cc

**Comment by fm3** [comment] 2021-01-21 20:31
It is used to discern between saved annotations (Explorational, Task, which are looked up in the annotations table) vs Compound Annotations (CompoundTask, CompoundProject, CompoundTaskType, which are created by merging all annotations of the respective project etc. There the id in the url is that of a project etc). 

We can either 
- (1) create an autodetect which traverses all the possible sources for the ID before returning failure, may be slightly slower
- (2) decide that this part of the url being empty means Explorational (those are usually the published ones)

I think it is useful to the user to immediately see in the url which type of annotation you are handling, so I would prefer option 2. What do you think?

**Comment by philippotto** [comment] 2021-01-22 08:29
> I think it is useful to the user to immediately see in the url which type of annotation you are handling

I'd assume that most users won't really profit from that information, but I might be wrong here.

I don't have strong feelings about this. The most consistent way would probably to remove the type-part from all URLs and then  traverse over all types on the back-end (possibly ordered by likelihood + early out?). The speed could be negligible, anyway, since looking up an annotation is not a high-frequency action (compared to other requests).

Option (2) would be fine to me, too, though.

And a third option:
- (3) Find a better name than `Explorational`. For example, `raw`, `simple`, `unit` or whatever (I don't like these suggestions in particular, but maybe someone has a better idea)

**Comment by hotzenklotz** [comment] 2022-04-25 12:34
Related / duplicate of https://github.com/scalableminds/webknossos/issues/6156

**Closed** 2022-07-27 08:48 UTC
Labels: enhancement, frontend
