### ISSUE TITLE
show “supported at a smaller zoom level.” message only in brush mode?

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4358] opened 2019-12-09 09:31 UTC
…not sure how, but we need to make this “Segmentation data and volume tracing is only fully supported at a smaller zoom level.” message less obtrusive. I’m clicking “create tracing” in a dataset to create a skeleton, it creates a hybrid, though, and I get this message whenever I change something in the view.

**Comment by philippotto** [comment] 2020-01-07 13:52
I agree that the message can be annoying! However, I think, it's like that because the actual segmentation/volume data is hidden when not being in mag 1. This can be confusing to the user (regardless of the active tool). But, there's certainly a less obtrusive way to make this obvious to the user.

**Comment by philippotto** [comment] 2020-07-29 15:36
Also see #4471 for how to make such a message not too obtrusive.

**Comment by philippotto** [comment] 2020-08-03 11:53
Related to https://github.com/scalableminds/webknossos/issues/4002.

**Comment by philippotto** [comment] 2020-08-03 14:00
duplicate of #4002.

**Closed by philippotto** 2020-08-03 14:00 UTC
Labels: frontend, hybrid
