### ISSUE TITLE
Changing the viewport distorts 3D view

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#4064] opened 2019-05-03 14:58 UTC
The 3D viewport doesn't survive a large layout change such as maximizing one panel:

![May-03-2019 16-57-17](https://user-images.githubusercontent.com/335438/57145984-9b6adc00-6dc4-11e9-9972-b0f520d45ae0.gif)

**Comment by MichaelBuessemeyer** [comment] 2019-05-06 15:51
I am pretty sure that's a duplicate of #3882.

**Closed** 2019-05-09 11:06 UTC
Labels: bug, frontend
