### ISSUE TITLE
Fix cursor when hovering a bounding box

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [scalableminds/webknossos#8119] opened 2024-10-09 13:57 UTC
There is currently no consistent cursor change, when hovering a bounding box when the bounding box tool is active.

## Context

When the bounding box tool is active, the user should get a hint what can be done when hovering a bounding box. This hint was previously given by changing the cursor icon. But it seems flaky right now and almost never appears.

## Expected Behavior

When hovering a bounding box while the bounding box tool is active, the cursor should change indicating that the bbox can be resized. 

## Current Behavior

The cursor doesn't change only in some rare cases the changed cursor is shortly shown to the user

## Steps to Reproduce the bug

1. Open an annotation
2. Create a bounding box
3. active the bbox tool & hover the bbox edges
4. Most of the time no cursor change should be visible

## Your Environment for bug

- Was observed on Mac with Safari / Chrome (don't really know which of them)

**Comment by dieknolle3333** [comment] 2024-10-17 11:27
Thank you for reporting this! Unfortunately, I cannot reproduce this on Ubuntu (neither Brave/Chromium nor Firefox). We also were not able to reproduce this on a Mac (neither Safari nor Chrome).

**Comment by MichaelBuessemeyer** [comment] 2024-10-17 11:40
> Thank you for reporting this! Unfortunately, I cannot reproduce this on Ubuntu (neither Brave/Chromium nor Firefox). We also were not able to reproduce this on a Mac (neither Safari nor Chrome). Can you help me out?

Hmm strange. Thanks for investigating this. @valentin-pinkau showed me this bug on one of his annotations. Maybe we should have linked the annotation as it seems to maybe have something to do with the annotation :thinking: ?!

Anyway. I also gave it a quick check and can't reproduce this either.
=> I'd say if @valentin-pinkau cant reproduce this, this issue should be closed and re-opened if it re-occurs.

**Comment by dieknolle3333** [comment] 2024-10-17 11:44
It was solved after a reboot :) I'll close this for now.

**Closed by dieknolle3333** 2024-10-17 11:44 UTC
Labels: bug, frontend
