### ISSUE TITLE
admin of parent team

### ISSUE THREAD

**Issue by kevinbbb87** [scalableminds/webknossos#1222] opened 2016-05-18 19:10 UTC
I just got the message
User Kevin Boergens can't be assigned administrative rights in team Baier Department because he doesnt belong to the teams parent team.
Why is that so? Also, in the view it still shows my rights as admin (until reload)

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1222/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment] 2018-02-05 13:22
Duplicate of #2160

**Closed by hotzenklotz** 2018-02-05 13:22 UTC
Labels: discussion, team-administration
