### ISSUE TITLE
for float datasets, allow manually specifying brightness range

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#4527] opened 2020-04-06 17:08 UTC
Since rendering floats entirely depends on the range, it would be desirable to allow the user to manually enter this brightness range, to support cases in which the histogram call fails (or does not cover all relevant data)

**Comment by normanrz** [comment] 2020-04-06 17:26
duplicate of #4526

**Closed by normanrz** 2020-04-06 17:26 UTC
Labels: frontend
