### ISSUE TITLE
Reload the histogram on layer reload

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos#5093] opened 2021-01-26 13:04 UTC
When reloading the data of a layer (via the circular arrow button in the layer settings) the histogram stays the same, even if the data changes drastically. Instead, the histogram should be reloaded as well, using the updated data.

**Comment by fm3** [comment] 2021-01-26 13:15
duplicate of #4479

**Closed by fm3** 2021-01-26 13:15 UTC

**Comment by jstriebel** [comment] 2021-01-26 13:19
Sorry, I searched the issues before, but for `historgram` :trollface:
