### ISSUE TITLE
Weird bucket loading behaviour in specific dataset

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#2707] opened 2018-06-07 15:02 UTC
Moving around in the `2018_05_16_MB_HCl31_st013_test_700` dataset on the master instance causes weird behavior. Buckets that are actually in the viewport get removed and then loaded again, the data in the xy and yz viewports looks distorted. Could be an issue related to the dataset scale, not sure.

**Comment by philippotto** [comment] 2018-06-08 13:22
@daniel-wer I cannot reproduce this issue on my pc. Can you?

**Comment by daniel-wer** [comment] 2018-06-11 14:31
Yep I can, I'll have a look!

**Comment by philippotto** [comment] 2018-06-12 08:10
For the record: During our investigation we determined that the dataset's scale `11.24, 11.24, 11.24` does not match the nature of the uniform-scaled ("anisotropic") resolutions `[2, 2, 1], [4, 4, 2], [8, 8, 4], ...`. Therefore, we can close this, I think. We should keep this in mind in case we get error reports regarding that.

**Closed by philippotto** 2018-06-12 08:10 UTC
Labels: bug, frontend
